import type { PlatformId } from "@/lib/types";

export type PaidMediaCategory =
  | "portal"
  | "hao"
  | "industry"
  | "yellow"
  | "community";

export const PAID_MEDIA_CATEGORIES: {
  id: PaidMediaCategory;
  label: string;
}[] = [
  { id: "hao", label: "媒体号" },
  { id: "portal", label: "门户新闻" },
  { id: "industry", label: "行业媒体" },
  { id: "yellow", label: "黄页" },
  { id: "community", label: "社区专栏" },
];

export type PaidMediaSku = {
  id: string;
  name: string;
  site: string;
  href: string;
  category: PaidMediaCategory;
  priceYuan: number;
  hours: number;
  newsSource: boolean;
  geo: boolean;
  aiTags: string[];
  note: string;
  ownPlatformId?: PlatformId;
};

export const PAID_MEDIA_SKUS: PaidMediaSku[] = [
  {
    id: "baijiahao",
    name: "百家号",
    site: "百度",
    href: "https://baijiahao.baidu.com",
    category: "hao",
    priceYuan: 80,
    hours: 4,
    newsSource: true,
    geo: true,
    aiTags: ["文心一言"],
    note: "百度系信息流，搜索和文心都容易碰到。",
    ownPlatformId: "baijiahao",
  },
  {
    id: "toutiao",
    name: "头条号",
    site: "今日头条",
    href: "https://www.toutiao.com",
    category: "hao",
    priceYuan: 150,
    hours: 4,
    newsSource: true,
    geo: true,
    aiTags: ["豆包"],
    note: "字节信息流。也可走自有号草稿。",
    ownPlatformId: "toutiao",
  },
  {
    id: "sohu",
    name: "搜狐号",
    site: "搜狐",
    href: "https://www.sohu.com",
    category: "hao",
    priceYuan: 120,
    hours: 6,
    newsSource: true,
    geo: true,
    aiTags: ["DeepSeek"],
    note: "门户号，收录稳。",
    ownPlatformId: "sohu",
  },
  {
    id: "netease",
    name: "网易号",
    site: "网易",
    href: "https://www.163.com",
    category: "hao",
    priceYuan: 180,
    hours: 6,
    newsSource: true,
    geo: true,
    aiTags: ["DeepSeek"],
    note: "网易新闻源常见引用。",
    ownPlatformId: "netease",
  },
  {
    id: "qiehao",
    name: "企鹅号",
    site: "腾讯",
    href: "https://om.qq.com",
    category: "hao",
    priceYuan: 160,
    hours: 6,
    newsSource: true,
    geo: true,
    aiTags: ["元宝"],
    note: "腾讯内容生态，元宝常引。",
    ownPlatformId: "qiehao",
  },
  {
    id: "dayu",
    name: "大鱼号",
    site: "UC / 阿里",
    href: "https://mp.dayu.com",
    category: "hao",
    priceYuan: 90,
    hours: 8,
    newsSource: true,
    geo: true,
    aiTags: ["通义千问"],
    note: "阿里内容号。",
    ownPlatformId: "dayu",
  },
  {
    id: "ifeng-finance",
    name: "凤凰网·财经",
    site: "凤凰网",
    href: "https://www.ifeng.com",
    category: "portal",
    priceYuan: 2800,
    hours: 24,
    newsSource: true,
    geo: true,
    aiTags: ["DeepSeek", "豆包", "元宝", "Kimi"],
    note: "门户频道稿，适合品牌信任。",
  },
  {
    id: "china-com-news",
    name: "中华网·快讯",
    site: "中华网",
    href: "https://www.china.com",
    category: "portal",
    priceYuan: 1600,
    hours: 12,
    newsSource: true,
    geo: true,
    aiTags: ["DeepSeek", "文心一言"],
    note: "快讯栏目，出稿快。",
  },
  {
    id: "thepaper",
    name: "澎湃新闻",
    site: "澎湃",
    href: "https://www.thepaper.cn",
    category: "portal",
    priceYuan: 3200,
    hours: 48,
    newsSource: true,
    geo: true,
    aiTags: ["DeepSeek", "豆包", "Kimi"],
    note: "长三角品牌、活动信息披露。",
  },
  {
    id: "36kr",
    name: "36氪",
    site: "36氪",
    href: "https://36kr.com",
    category: "industry",
    priceYuan: 2200,
    hours: 48,
    newsSource: true,
    geo: true,
    aiTags: ["DeepSeek", "豆包"],
    note: "创投和科技公司常用。",
  },
  {
    id: "huxiu",
    name: "虎嗅",
    site: "虎嗅",
    href: "https://www.huxiu.com",
    category: "industry",
    priceYuan: 1800,
    hours: 48,
    newsSource: true,
    geo: true,
    aiTags: ["DeepSeek", "Kimi"],
    note: "商业评论向，适合观点稿。",
  },
  {
    id: "tmtpost",
    name: "钛媒体",
    site: "钛媒体",
    href: "https://www.tmtpost.com",
    category: "industry",
    priceYuan: 1500,
    hours: 48,
    newsSource: true,
    geo: true,
    aiTags: ["DeepSeek"],
    note: "TMT 行业稿。",
  },
  {
    id: "woshipm",
    name: "人人都是产品经理",
    site: "人人都是产品经理",
    href: "https://www.woshipm.com",
    category: "community",
    priceYuan: 260,
    hours: 24,
    newsSource: false,
    geo: true,
    aiTags: ["DeepSeek"],
    note: "产品和方法论文。也可自有号。",
    ownPlatformId: "woshipm",
  },
  {
    id: "zhihu",
    name: "知乎",
    site: "知乎",
    href: "https://www.zhihu.com",
    category: "community",
    priceYuan: 200,
    hours: 12,
    newsSource: false,
    geo: true,
    aiTags: ["DeepSeek", "豆包", "Kimi"],
    note: "问答和文章都常被模型引用。也可自有号。",
    ownPlatformId: "zhihu",
  },
  {
    id: "csdn",
    name: "CSDN",
    site: "CSDN",
    href: "https://www.csdn.net",
    category: "community",
    priceYuan: 120,
    hours: 8,
    newsSource: false,
    geo: true,
    aiTags: ["DeepSeek", "通义千问"],
    note: "技术品牌、开发者向。",
    ownPlatformId: "csdn",
  },
  {
    id: "juejin",
    name: "掘金",
    site: "掘金",
    href: "https://juejin.cn",
    category: "community",
    priceYuan: 140,
    hours: 8,
    newsSource: false,
    geo: true,
    aiTags: ["DeepSeek"],
    note: "开发者社区。",
    ownPlatformId: "juejin",
  },
  {
    id: "shunqi",
    name: "顺企网企业新闻",
    site: "顺企网",
    href: "https://www.11467.com",
    category: "yellow",
    priceYuan: 60,
    hours: 12,
    newsSource: false,
    geo: true,
    aiTags: [],
    note: "B2B 黄页，本地和行业检索。",
    ownPlatformId: "shunqi",
  },
  {
    id: "bafang",
    name: "八方资源网",
    site: "八方资源网",
    href: "https://www.b2b168.com",
    category: "yellow",
    priceYuan: 70,
    hours: 12,
    newsSource: false,
    geo: true,
    aiTags: [],
    note: "供求黄页。",
    ownPlatformId: "bafang",
  },
  {
    id: "hc360",
    name: "慧聪网",
    site: "慧聪网",
    href: "https://www.hc360.com",
    category: "yellow",
    priceYuan: 180,
    hours: 24,
    newsSource: false,
    geo: true,
    aiTags: [],
    note: "行业 B2B，适合产品和公司介绍。",
  },
  {
    id: "yicai",
    name: "第一财经",
    site: "第一财经",
    href: "https://www.yicai.com",
    category: "portal",
    priceYuan: 3600,
    hours: 48,
    newsSource: true,
    geo: true,
    aiTags: ["DeepSeek", "豆包", "元宝"],
    note: "财经权威出处。",
  },
  {
    id: "people-com",
    name: "人民网",
    site: "人民日报社",
    href: "https://www.people.com.cn",
    category: "portal",
    priceYuan: 4800,
    hours: 48,
    newsSource: true,
    geo: true,
    aiTags: ["DeepSeek", "文心一言", "豆包"],
    note: "党政和品牌公信力常用。",
  },
  {
    id: "xinhua",
    name: "新华网",
    site: "新华社",
    href: "https://www.xinhuanet.com",
    category: "portal",
    priceYuan: 4500,
    hours: 48,
    newsSource: true,
    geo: true,
    aiTags: ["DeepSeek", "文心一言"],
    note: "国家级新闻源。",
  },
  {
    id: "cctv",
    name: "央视网",
    site: "央视",
    href: "https://www.cctv.com",
    category: "portal",
    priceYuan: 4200,
    hours: 48,
    newsSource: true,
    geo: true,
    aiTags: ["DeepSeek", "文心一言"],
    note: "总台站点，适合重大发布。",
  },
  {
    id: "chinanews",
    name: "中国新闻网",
    site: "中新社",
    href: "https://www.chinanews.com.cn",
    category: "portal",
    priceYuan: 2600,
    hours: 24,
    newsSource: true,
    geo: true,
    aiTags: ["DeepSeek", "豆包"],
    note: "中新社稿源，转载面广。",
  },
  {
    id: "gmw",
    name: "光明网",
    site: "光明日报",
    href: "https://www.gmw.cn",
    category: "portal",
    priceYuan: 2400,
    hours: 24,
    newsSource: true,
    geo: true,
    aiTags: ["DeepSeek"],
    note: "文化教育向门户。",
  },
  {
    id: "cnr",
    name: "央广网",
    site: "央广",
    href: "https://www.cnr.cn",
    category: "portal",
    priceYuan: 2200,
    hours: 24,
    newsSource: true,
    geo: true,
    aiTags: ["DeepSeek"],
    note: "广播总台新闻源。",
  },
  {
    id: "youth",
    name: "中国青年网",
    site: "中青网",
    href: "https://www.youth.cn",
    category: "portal",
    priceYuan: 1800,
    hours: 24,
    newsSource: true,
    geo: true,
    aiTags: ["DeepSeek"],
    note: "青年和校园向。",
  },
  {
    id: "huanqiu",
    name: "环球网",
    site: "环球时报",
    href: "https://www.huanqiu.com",
    category: "portal",
    priceYuan: 2000,
    hours: 24,
    newsSource: true,
    geo: true,
    aiTags: ["DeepSeek", "豆包"],
    note: "时政国际向。",
  },
  {
    id: "chinadaily",
    name: "中国日报网",
    site: "China Daily",
    href: "https://cn.chinadaily.com.cn",
    category: "portal",
    priceYuan: 2800,
    hours: 48,
    newsSource: true,
    geo: true,
    aiTags: ["DeepSeek"],
    note: "中英双语，适合出海品牌。",
  },
  {
    id: "ce-cn",
    name: "中国经济网",
    site: "经济日报",
    href: "https://www.ce.cn",
    category: "portal",
    priceYuan: 2100,
    hours: 24,
    newsSource: true,
    geo: true,
    aiTags: ["DeepSeek", "元宝"],
    note: "经济政策和企业稿。",
  },
  {
    id: "eastday",
    name: "东方网",
    site: "东方网",
    href: "https://www.eastday.com",
    category: "portal",
    priceYuan: 1200,
    hours: 12,
    newsSource: true,
    geo: true,
    aiTags: ["豆包"],
    note: "上海地方门户。",
    ownPlatformId: "dongfang",
  },
  {
    id: "qianlong",
    name: "千龙网",
    site: "千龙网",
    href: "https://www.qianlong.com",
    category: "portal",
    priceYuan: 1100,
    hours: 12,
    newsSource: true,
    geo: true,
    aiTags: ["文心一言"],
    note: "北京地方新闻源。",
  },
  {
    id: "hexun",
    name: "和讯网",
    site: "和讯",
    href: "https://www.hexun.com",
    category: "industry",
    priceYuan: 900,
    hours: 24,
    newsSource: true,
    geo: true,
    aiTags: ["DeepSeek"],
    note: "财经垂直。",
  },
  {
    id: "sina-news",
    name: "新浪新闻",
    site: "新浪",
    href: "https://news.sina.com.cn",
    category: "portal",
    priceYuan: 1600,
    hours: 12,
    newsSource: true,
    geo: true,
    aiTags: ["DeepSeek", "元宝"],
    note: "门户转载面大。",
    ownPlatformId: "sinakandian",
  },
  {
    id: "yidian",
    name: "一点号",
    site: "一点资讯",
    href: "https://www.yidianzixun.com",
    category: "hao",
    priceYuan: 70,
    hours: 8,
    newsSource: true,
    geo: true,
    aiTags: [],
    note: "信息流号，价格低。",
    ownPlatformId: "yidian",
  },
  {
    id: "dafeng",
    name: "大风号",
    site: "凤凰网",
    href: "https://www.ifeng.com",
    category: "hao",
    priceYuan: 130,
    hours: 8,
    newsSource: true,
    geo: true,
    aiTags: ["DeepSeek", "豆包"],
    note: "凤凰创作者号，比频道稿便宜。",
    ownPlatformId: "dafeng",
  },
  {
    id: "jiemian",
    name: "界面新闻",
    site: "界面",
    href: "https://www.jiemian.com",
    category: "industry",
    priceYuan: 2400,
    hours: 48,
    newsSource: true,
    geo: true,
    aiTags: ["DeepSeek", "Kimi"],
    note: "商业财经稿。",
  },
  {
    id: "caixin",
    name: "财新",
    site: "财新传媒",
    href: "https://www.caixin.com",
    category: "industry",
    priceYuan: 5000,
    hours: 72,
    newsSource: true,
    geo: true,
    aiTags: ["DeepSeek", "Kimi"],
    note: "高端财经，审核严。",
  },
  {
    id: "nbd",
    name: "每日经济新闻",
    site: "每经",
    href: "https://www.nbd.com.cn",
    category: "industry",
    priceYuan: 1900,
    hours: 24,
    newsSource: true,
    geo: true,
    aiTags: ["DeepSeek"],
    note: "上市公司和产业稿常用。",
  },
];

const SKU_MAP = new Map(PAID_MEDIA_SKUS.map((sku) => [sku.id, sku]));

export function getPaidMediaSku(id: string): PaidMediaSku | undefined {
  return SKU_MAP.get(id);
}

export function formatYuan(value: number): string {
  return `¥${value}`;
}

export type PaidOrderStatus =
  | "pending"
  | "accepted"
  | "published"
  | "failed"
  | "cancelled";

export type PaidOrderItem = {
  id: string;
  order_id: string;
  sku_id: string;
  sku_name: string;
  price_yuan: number;
  status: PaidOrderStatus;
  result_url: string | null;
};

export type PaidOrder = {
  id: string;
  workspace_id: string;
  article_id: string;
  article_title: string;
  status: PaidOrderStatus;
  total_yuan: number;
  note: string;
  created_at: string;
  updated_at: string;
  items: PaidOrderItem[];
};
